
services:
  producer:
    cpu_count: 4
    image: python:3
    command: python -u myfiles/produce_producer.py #sh myfiles/script.sh
    volumes:
      - shared-data:/data:z
      - .:/myfiles:ro

volumes:
  shared-data:
    external: true
    name: shared-data

